import React from 'react';

import { css, Global } from '@emotion/react';

const styles = css`
  * {
    outline: none;
    box-sizing: border-box;
    -webkit-font-smoothing: antialiased;
  }

  body {
    min-height: 100vh;
    height: calc(var(--vh, 1vh) * 100);
    margin: 0px;
    background-color: #181a1c;
  }

  @font-face {
    font-family: 'corners';
    src: url('fonts/corners.eot?10496212');
    src: url('fonts/corners.eot?10496212#iefix') format('embedded-opentype'),
      url('fonts/corners.woff2?10496212') format('woff2'),
      url('fonts/corners.woff?10496212') format('woff'),
      url('fonts/corners.ttf?10496212') format('truetype'),
      url('fonts/corners.svg?10496212#corners') format('svg');
    font-weight: normal;
    font-style: normal;
  }

  @font-face {
    font-family: 'mokoto_glitch_mark_iiregular';
    src: url('fonts/mokoto_glitch_mark_2-webfont.woff2') format('woff2'),
      url('fonts/mokoto_glitch_mark_2-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;
  }

  @font-face {
    font-family: 'mokoto_glitchregular';
    src: url('fonts/mokoto_glitch-webfont.woff2') format('woff2'),
      url('fonts/mokoto_glitch-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;
  }

  /*! Generated by Font Squirrel (https://www.fontsquirrel.com) on May 15, 2021 */

  @font-face {
    font-family: 'opensans';
    src: url('fonts/opensans-light-webfont.woff2') format('woff2'),
      url('fonts/opensans-light-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;
  }

  @font-face {
    font-family: 'optician';
    src: url('fonts/optician-sans-webfont.woff2') format('woff2'),
      url('fonts/optician-sans-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;
  }

  @font-face {
    font-family: 'morganite';
    src: url('fonts/Morganite-Light.woff2') format('woff2'),
      url('fonts/Morganite-Light.woff') format('woff');
    font-weight: normal;
    font-style: normal;
  }

  @font-face {
    font-family: 'mokto_glitch_mark_outline';
    src: url('fonts/MoktoGlitchMarkoutline.ttf');
    font-weight: normal;
    font-style: normal;
  }

  h1 {
    font-family: 'mokoto_glitch_mark_iiregular', sans-serif;
    font-size: 28px;
    text-transform: uppercase;
    letter-spacing: 3px;
    font-weight: 100;
    margin: 0;
    @media only screen and (min-width: 1024px) {
      font-size: 42px;
    }
  }

  h2 {
    font-family: 'optician', sans-serif;
    font-size: 14px;
    text-transform: uppercase;
    letter-spacing: 3px;
    font-weight: 100;
    margin: 0;
  }

  h3 {
    font-family: 'optician', sans-serif;
    font-size: 14px;
    text-transform: uppercase;
    letter-spacing: 3px;
    font-weight: 100;
    margin: 0;
  }
  p {
    font-family: 'opensans', sans-serif;
    font-size: 13px;
    line-height: 25px;
  }

  ul {
    list-style-type: none;
    padding-inline-start: 0;
  }
  li {
    font-family: 'optician', sans-serif;
    font-size: 14px;
    padding: none;
    font-weight: 100;
    margin-bottom: 20px;
  }
`;

const GlobalStyle = () => <Global styles={styles} />;

export default GlobalStyle;
